version: '3'
services:
    client:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.client
        ports:
            - ${CLIENT_PORT}:8501
        command: -- --server_url ${SERVER_URL}
        depends_on:
            - server

    server:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.server
        volumes:
            - ./resources/data/:/core/data/
        ports:
            - ${SERVER_PORT}:5000
        command: --data_path data/${DATA_FILE}
